title: TRIA Map Making Codex
description: A resource for new and experienced TRIA.os map makers
theme: just-the-docs

url: https://tactaillike.github.io/tria-mapmaking-codex

aux_links:
  Repository: https://github.com/tactaillike/tria-mapmaking-codex 

nav_enabled: true

heading_anchors: true
