title: TRIA Map Making Codex
description: A resource for new and experienced TRIA.os map makers
theme: just-the-docs

url: https://tactaillike.github.io/tria-mapmaking-codex

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark